<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Watchout.Desktop</RootNamespace>
    <AssemblyName>WatchoutProducer</AssemblyName>
    <Product>WATCHOUT Producer</Product>
    <AssemblyTitle>WATCHOUT Producer</AssemblyTitle>
    <Version>7.8.12</Version>
    <FileVersion>7.8.12</FileVersion>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Watchout.Core\Watchout.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\app.png" />
    <Resource Include="Assets\app.ico" />
  </ItemGroup>
</Project>
